# Generated by Django 2.1.7 on 2020-02-22 02:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('League', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='easy',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='easy', to='League.Difficulty'),
        ),
        migrations.AlterField(
            model_name='song',
            name='expert',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='expert', to='League.Difficulty'),
        ),
        migrations.AlterField(
            model_name='song',
            name='expert_plus',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='expert_plus', to='League.Difficulty'),
        ),
        migrations.AlterField(
            model_name='song',
            name='hard',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hard', to='League.Difficulty'),
        ),
        migrations.AlterField(
            model_name='song',
            name='normal',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='normal', to='League.Difficulty'),
        ),
    ]
