# Generated by Django 2.1.7 on 2020-02-17 19:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('League', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Score',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='League.Game')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='League.Player')),
                ('song', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='League.Song')),
            ],
        ),
    ]
