# Generated by Django 2.1.7 on 2020-02-17 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('League', '0003_auto_20200217_2230'),
    ]

    operations = [
        migrations.AddField(
            model_name='score',
            name='date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
