# Generated by Django 2.1.7 on 2020-02-24 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('League', '0003_auto_20200222_2226'),
    ]

    operations = [
        migrations.AddField(
            model_name='season',
            name='sponsor_name',
            field=models.CharField(default='VR Gaming Room', max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='player',
            name='created_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='playlist',
            name='created_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='score',
            name='created_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='song',
            name='created_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
