# Generated by Django 2.1.7 on 2020-02-19 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('League', '0004_score_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='logo',
            field=models.FileField(default='', null=True, upload_to='documents/%Y/%m/%d/'),
        ),
    ]
