# Generated by Django 2.1.7 on 2020-02-24 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('League', '0004_auto_20200224_1623'),
    ]

    operations = [
        migrations.AlterField(
            model_name='season',
            name='finishing_at',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='season',
            name='name',
            field=models.CharField(max_length=20, unique_for_month='starting_at'),
        ),
    ]
