# Generated by Django 2.1.7 on 2020-02-26 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('League', '0005_auto_20200224_1907'),
    ]

    operations = [
        migrations.AlterField(
            model_name='season',
            name='name',
            field=models.CharField(max_length=20, unique_for_date='starting_at'),
        ),
    ]
