# Generated by Django 2.1.7 on 2020-02-26 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('League', '0006_auto_20200226_1242'),
    ]

    operations = [
        migrations.AlterField(
            model_name='season',
            name='name',
            field=models.CharField(max_length=20),
        ),
    ]
