# Generated by Django 2.1.7 on 2020-02-26 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('League', '0007_auto_20200226_1243'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='key',
            field=models.CharField(blank=True, max_length=40, primary_key=True, serialize=False),
        ),
    ]
