# Generated by Django 2.1.7 on 2020-02-26 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('League', '0009_auto_20200226_1931'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playlist',
            name='songs',
            field=models.ManyToManyField(limit_choices_to={'game': True}, related_name='song_key', to='League.Song'),
        ),
    ]
