# Generated by Django 2.1.7 on 2020-02-27 15:12

from django.db import migrations
import smart_selects.db_fields


class Migration(migrations.Migration):

    dependencies = [
        ('League', '0012_auto_20200227_1806'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='playlist',
            name='songs',
        ),
        migrations.AddField(
            model_name='playlist',
            name='songs',
            field=smart_selects.db_fields.ChainedManyToManyField(chained_field='game', chained_model_field='game', horizontal=True, to='League.Song', verbose_name='songs'),
        ),
    ]
