# Generated by Django 2.1.7 on 2020-02-27 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('League', '0013_auto_20200227_1812'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='country',
            field=models.CharField(blank=True, max_length=3),
        ),
        migrations.AddField(
            model_name='player',
            name='profile_pic',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='player',
            name='real_name',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='player',
            name='steam_link',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='player',
            name='steam_uid',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='player',
            name='timezone',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='achievement',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='game',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='player',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='playlist',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='season',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='season',
            name='sponsor_name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='song',
            name='level_author_name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='song',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='song',
            name='song_author_name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='song',
            name='sub_name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='type',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='week',
            name='name',
            field=models.CharField(editable=False, max_length=50),
        ),
    ]
