# Generated by Django 2.1.7 on 2020-02-27 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('League', '0014_auto_20200228_0004'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='timezone',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
