# Generated by Django 2.1.7 on 2020-03-02 15:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('League', '0016_auto_20200302_0849'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='season',
            options={'verbose_name': 'League Season', 'verbose_name_plural': 'League Seasons'},
        ),
        migrations.AddField(
            model_name='type',
            name='is_daily',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='game',
            name='slug',
            field=models.SlugField(allow_unicode=True, blank=True, verbose_name='Page URL'),
        ),
        migrations.AlterField(
            model_name='player',
            name='slug',
            field=models.SlugField(allow_unicode=True, blank=True, verbose_name='Page URL'),
        ),
        migrations.AlterField(
            model_name='playlist',
            name='slug',
            field=models.SlugField(allow_unicode=True, blank=True, verbose_name='Page URL'),
        ),
        migrations.AlterField(
            model_name='season',
            name='slug',
            field=models.SlugField(allow_unicode=True, blank=True, verbose_name='Page URL'),
        ),
        migrations.AlterField(
            model_name='song',
            name='slug',
            field=models.SlugField(allow_unicode=True, blank=True, verbose_name='Page URL'),
        ),
        migrations.AlterField(
            model_name='week',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='week',
            name='season',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='League.Season'),
        ),
        migrations.AlterField(
            model_name='week',
            name='slug',
            field=models.SlugField(allow_unicode=True, blank=True, verbose_name='Page URL'),
        ),
        migrations.AlterField(
            model_name='week',
            name='starting_at',
            field=models.DateField(editable=False, null=True),
        ),
    ]
