# Generated by Django 2.1.7 on 2020-03-02 15:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('League', '0017_auto_20200302_1853'),
    ]

    operations = [
        migrations.RenameField(
            model_name='type',
            old_name='week_count',
            new_name='count',
        ),
    ]
