# Generated by Django 2.1.7 on 2020-03-03 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('League', '0018_auto_20200302_1854'),
    ]

    operations = [
        migrations.AddField(
            model_name='season',
            name='difficulty',
            field=models.CharField(choices=[('EX', 'Expert'), ('HD', 'Hard'), ('NM', 'Normal'), ('EP', 'Expert Plus'), ('EZ', 'Easy')], default='HD', max_length=2),
        ),
    ]
