# Generated by Django 2.1.7 on 2020-03-04 15:44

from django.db import migrations, models
import smart_selects.db_fields


class Migration(migrations.Migration):

    dependencies = [
        ('League', '0020_auto_20200303_2125'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='type',
            name='difficulty',
        ),
        migrations.AddField(
            model_name='playlist',
            name='difficulty',
            field=models.CharField(choices=[('EX', 'Expert'), ('HD', 'Hard'), ('NM', 'Normal'), ('EP', 'Expert Plus'), ('EZ', 'Easy')], default='HD', max_length=2),
        ),
        migrations.AlterField(
            model_name='playlist',
            name='songs',
            field=smart_selects.db_fields.ChainedManyToManyField(auto_choose=True, blank=True, chained_field='game', chained_model_field='game', horizontal=True, to='League.Song', verbose_name='songs'),
        ),
    ]
