# Generated by Django 2.1.7 on 2020-03-04 15:53

from django.db import migrations, models
import smart_selects.db_fields


class Migration(migrations.Migration):

    dependencies = [
        ('League', '0021_auto_20200304_1844'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='week',
            name='playlist',
        ),
        migrations.AddField(
            model_name='season',
            name='difficulty',
            field=models.CharField(choices=[('EX', 'Expert'), ('HD', 'Hard'), ('NM', 'Normal'), ('EP', 'Expert Plus'), ('EZ', 'Easy')], default='HD', max_length=2),
        ),
        migrations.AddField(
            model_name='week',
            name='songs',
            field=smart_selects.db_fields.ChainedManyToManyField(auto_choose=True, blank=True, chained_field='season.game', chained_model_field='game', horizontal=True, to='League.Song', verbose_name='songs'),
        ),
    ]
