# Generated by Django 2.1.7 on 2020-03-04 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('League', '0022_auto_20200304_1853'),
    ]

    operations = [
        migrations.AlterField(
            model_name='week',
            name='songs',
            field=models.ManyToManyField(blank=True, to='League.Song', verbose_name='songs'),
        ),
    ]
