# Generated by Django 2.1.7 on 2020-03-04 16:45

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('League', '0023_auto_20200304_1856'),
    ]

    operations = [
        migrations.AlterField(
            model_name='season',
            name='starting_at',
            field=models.DateField(default=datetime.datetime(2020, 3, 4, 16, 45, 9, 906687, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
