# Generated by Django 2.1.7 on 2020-03-04 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('League', '0024_auto_20200304_1945'),
    ]

    operations = [
        migrations.AlterField(
            model_name='week',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
