# Generated by Django 2.1.7 on 2020-03-06 01:15

import datetime
import django.core.validators
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('League', '0025_auto_20200304_2002'),
    ]

    operations = [
        migrations.AddField(
            model_name='type',
            name='song_count',
            field=models.IntegerField(default=10, validators=[django.core.validators.MaxValueValidator(20), django.core.validators.MinValueValidator(1)]),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='playlist',
            name='difficulty',
            field=models.CharField(choices=[('EZ', 'Easy'), ('NM', 'Normal'), ('HD', 'Hard'), ('EX', 'Expert'), ('EP', 'Expert Plus')], default='HD', max_length=2),
        ),
        migrations.AlterField(
            model_name='week',
            name='starting_at',
            field=models.DateField(default=datetime.datetime(2020, 3, 6, 1, 15, 47, 427469, tzinfo=utc), editable=False),
            preserve_default=False,
        ),
    ]
