# Generated by Django 2.1.7 on 2020-03-06 03:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('League', '0028_playlist_difficulty'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='playlist',
            name='difficulty',
        ),
    ]
