# Generated by Django 2.1.7 on 2020-03-06 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('League', '0029_remove_playlist_difficulty'),
    ]

    operations = [
        migrations.AddField(
            model_name='playlist',
            name='difficulty',
            field=models.CharField(choices=[('EZ', 'Easy'), ('NM', 'Normal'), ('HD', 'Hard'), ('EX', 'Expert'), ('EP', 'Expert Plus')], default='HD', max_length=2),
        ),
    ]
