# Generated by Django 2.1.7 on 2020-03-06 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('League', '0031_auto_20200306_0616'),
    ]

    operations = [
        migrations.AddField(
            model_name='score',
            name='bad_cuts_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='score',
            name='difficulty_rank',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='score',
            name='full_combo',
            field=models.BooleanField(default=0),
        ),
        migrations.AddField(
            model_name='score',
            name='good_cuts_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='score',
            name='max_combo',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='score',
            name='modified_score',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='score',
            name='note_jump_movement_speed',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='score',
            name='note_jump_start_beat_offset',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='score',
            name='raw_score',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='score',
            name='rawscore',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='game',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='playlist',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='score',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='season',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='song',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='week',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
