# Generated by Django 2.1.7 on 2020-03-07 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('League', '0032_auto_20200306_0635'),
    ]

    operations = [
        migrations.AddField(
            model_name='season',
            name='picture',
            field=models.FileField(default='', null=True, upload_to='season_pics/%Y/%m/%d/'),
        ),
    ]
