# Generated by Django 2.1.7 on 2020-03-07 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('League', '0033_season_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='season',
            name='picture',
            field=models.FileField(default='/static/league/img/vrlogo.png', null=True, upload_to='season_pics/%Y/%m/%d/'),
        ),
    ]
