# Generated by Django 2.1.7 on 2020-03-07 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('League', '0038_auto_20200307_2332'),
    ]

    operations = [
        migrations.AlterField(
            model_name='season',
            name='picture',
            field=models.ImageField(blank=True, default='documents/vrlogo.png', upload_to='season_pics/%Y/%m/%d/'),
        ),
    ]
