# Generated by Django 2.1.7 on 2020-03-08 00:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('League', '0039_auto_20200307_2334'),
    ]

    operations = [
        migrations.RenameField(
            model_name='player',
            old_name='total_point',
            new_name='total_score',
        ),
    ]
