# Generated by Django 2.1.7 on 2020-03-08 00:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('League', '0040_auto_20200308_0307'),
    ]

    operations = [
        migrations.RenameField(
            model_name='score',
            old_name='player',
            new_name='user',
        ),
    ]
