# Generated by Django 3.0.4 on 2020-03-14 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('League', '0041_auto_20200308_0310'),
    ]

    operations = [
        migrations.AddField(
            model_name='season',
            name='description',
            field=models.CharField(default='aciklama', max_length=500),
            preserve_default=False,
        ),
    ]
