# Generated by Django 3.0.4 on 2020-03-16 06:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('League', '0042_season_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('detail', models.CharField(max_length=500)),
                ('game_detail', models.CharField(blank=True, max_length=80, null=True)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='League.Player')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
