# Generated by Django 3.0.4 on 2020-03-16 11:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('League', '0043_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player', to='League.Player'),
        ),
    ]
