# Generated by Django 3.0.4 on 2020-03-16 11:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('League', '0045_auto_20200316_1443'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='player',
            new_name='user',
        ),
    ]
