# Generated by Django 3.0.4 on 2020-03-16 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('League', '0046_auto_20200316_1444'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='seasons',
            field=models.ManyToManyField(related_name='player_seasons', to='League.Season'),
        ),
    ]
