# Generated by Django 3.0.4 on 2020-03-21 18:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('League', '0047_player_seasons'),
    ]

    operations = [
        migrations.AddField(
            model_name='season',
            name='user_list',
            field=models.ManyToManyField(null=True, related_name='applied_users', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='week',
            name='season',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='season_week', to='League.Season'),
        ),
    ]
