# Generated by Django 3.0.4 on 2020-03-23 07:34

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('League', '0048_auto_20200321_2102'),
    ]

    operations = [
        migrations.AddField(
            model_name='score',
            name='week',
            field=models.ManyToManyField(blank=True, related_name='score', to='League.Week'),
        ),
        migrations.AlterField(
            model_name='season',
            name='user_list',
            field=models.ManyToManyField(blank=True, related_name='applied_users', to=settings.AUTH_USER_MODEL),
        ),
    ]
