# Generated by Django 3.0.4 on 2020-03-23 09:39

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('League', '0049_auto_20200323_1034'),
    ]

    operations = [
        migrations.AddField(
            model_name='week',
            name='finishing_at',
            field=models.DateField(default=datetime.datetime(2020, 3, 23, 9, 39, 48, 797268, tzinfo=utc), editable=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='score',
            name='week',
            field=models.ManyToManyField(blank=True, related_name='week_scores', to='League.Week'),
        ),
    ]
