# Generated by Django 3.0.4 on 2020-03-28 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('League', '0050_auto_20200323_1239'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlphaUsers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('steam_id', models.CharField(max_length=50)),
            ],
        ),
    ]
