# Generated by Django 3.0.4 on 2020-05-22 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('League', '0051_alphausers'),
    ]

    operations = [
        migrations.AddField(
            model_name='week',
            name='weight',
            field=models.IntegerField(default=1),
        ),
    ]
